import initTabNav from './modules/tabnav.js';
import initAccordeon from './modules/accordeon.js';
import initScrollSuave from './modules/scroll-suave.js';
import initAnimacaoScroll from './modules/scroll-animacao.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropDown from './modules/dropdown.js';
import initMenuMobile from './modules/menu-mobile.js';
import initAnimaNumeros from './modules/anima-numeros.js';
import initFuncionamento from './modules/funcionamento.js';

initTabNav();
initAccordeon();
initScrollSuave();
initAnimacaoScroll();
initModal();
initTooltip();
initDropDown();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();